server:
  port: 2991

spring:
  redis:
    database: 1
#    host: 127.0.0.1
#    port: 6379
    cluster:
      nodes:
        - 192.168.174.131:6379
        - 192.168.174.132:6379
        - 192.168.174.133:6379
        - 192.168.174.131:6380
        - 192.168.174.132:6380
        - 192.168.174.133:6380
    #    jedis:
    #使用lettuce连接池（推荐）
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: 3000
    timeout: 30000

