server:
  port: 2020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/the_course?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: aaaaaa